services:
  breaker-sotano:
    build: .
    container_name: breaker-sotano
    network_mode: host
    command: python -m app.device_server --config /app/configs/breaker_sotano.yaml
    volumes:
      - ./configs:/app/configs
      - ./app:/app/app
    restart: unless-stopped