device:
  name: breaker_sotano
  type: nsx_legacy
  bind: "0.0.0.0"
  port: 502
  unit_id: 255
  tick_interval: 0.2

behaviour:
  current_min: 110
  current_max: 130

command:
  plc_triggers:
    open:
      address: 11060
      bit: 0
      value: 1